name: Build and Deploy

on:
  push:
    branches:
      - develop
      - staging
      - production

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v1

    - name: Uses Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn # Extra Step

    - name: install deps with yarn
      id: yarn-install
      run: yarn

    - name: yarn build
      run: | # --prefer-offline flag to try to use cached downloads
        yarn run build